- LICENSE
- ansible_risk_insight/__init__.py
- ansible_risk_insight/analyzer.py
- ansible_risk_insight/annotator_base.py
- ansible_risk_insight/annotators/__init__.py
- ansible_risk_insight/annotators/ansible_builtin.py
- ansible_risk_insight/annotators/base.py
- ansible_risk_insight/annotators/sample_custom_annotator.py
- ansible_risk_insight/awx_utils.py
- ansible_risk_insight/context.py
- ansible_risk_insight/data_container.py
- ansible_risk_insight/finder.py
- ansible_risk_insight/key_test.py
- ansible_risk_insight/keyutil.py
- ansible_risk_insight/loader.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/parser.py
- ansible_risk_insight/risk_detector.py
- ansible_risk_insight/rules/__init__.py
- ansible_risk_insight/rules/base.py
- ansible_risk_insight/rules/download_exec.py
- ansible_risk_insight/rules/external_dependency.py
- ansible_risk_insight/rules/inbound_transfer.py
- ansible_risk_insight/rules/outbound_transfer.py
- ansible_risk_insight/rules/sample_custom_rule.py
- ansible_risk_insight/safe_glob.py
- ansible_risk_insight/tree.py
- ansible_risk_insight/variable_resolver.py
- pyproject.toml
Signed-off-by: Yuji Watanabe <muew@jp.ibm.com>
> add license

- ansible_risk_insight/annotators/annotator_base.py
- ansible_risk_insight/annotators/ansible_builtin.py
- ansible_risk_insight/annotators/risk_annotator_base.py
- ansible_risk_insight/annotators/sample_custom_annotator.py
- ansible_risk_insight/annotators/variable_resolver.py
- ansible_risk_insight/data_container.py
- ansible_risk_insight/rules/download_exec.py
- ansible_risk_insight/rules/inbound_transfer.py
- ansible_risk_insight/rules/outbound_transfer.py
Signed-off-by: Yuji Watanabe <muew@jp.ibm.com>
> move annotator base to annotators directory

- ansible_risk_insight/models.py
Signed-off-by: Richard Gebhardt <gebhardtr@redhat.com>
> fix: fix method name typo

- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/dependency_finder.py
- ansible_risk_insight/scanner.py
improve metadata
- include MANIFEST.json and FILES.json
- include meta/main.yml
- add author
> update dependency preparator

- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/dependency_finder.py
- support galaxy.yml
- enable to handle dependency version
- fix timestamp format and zone
> enable to get dependencies from galaxy.yml

- .github/workflows/lint.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- Makefile
- ansible_risk_insight/cli/__init__.py
- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/dependency_finder.py
- ansible_risk_insight/loader.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/utils.py
- setup.py
- test/test_scanner.py
issue: https://github.com/ansible/ansible-risk-insight/issues/42
- fix github actions
- fix test codes
> fix github action and test codes

- ansible_risk_insight/risk_detector.py
- ansible_risk_insight/rules/base.py
- ansible_risk_insight/rules/download_exec.py
- ansible_risk_insight/rules/external_dependency.py
- ansible_risk_insight/rules/inbound_transfer.py
- ansible_risk_insight/rules/outbound_transfer.py
- ansible_risk_insight/rules/sample_custom_rule.py
issue: https://github.com/ansible/ansible-risk-insight/issues/46
Add attributes such as "severity" and "tags" to rules and make them included in the output report of ARI
> add severity/tags/version to rules

- docs/customize_rules.md
- docs/installing.md
- add a doc for describing how to customize rules
- update the installing doc
Related issue: https://github.com/ansible/ansible-risk-insight/issues/40
> add custom rule and installing docs

- ansible_risk_insight/models.py
> fix mutating rule bug

- ansible_risk_insight/annotators/ansible.builtin/uri.py
- ansible_risk_insight/finder.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/parser.py
- ansible_risk_insight/rules/P001_module_name_validation.py
- ansible_risk_insight/rules/P002_module_argument_key_validation.py
- ansible_risk_insight/rules/P003_module_argument_value_validation.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/tree.py
- test/test_scanner.py
- fix multiple rule-related bugs 
- default rule conditions
- mutating rule output
- annotator small bug
- fix for improving scanning speed
- fix test code
> fix bugs related to rule evaluation

- ansible_risk_insight/__init__.py
- update cli to show a help when no operations are specified
> add top level help to cli

- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/rules/P003_module_argument_value_validation.py
- change to use str for arg spec type
> change to use str for arg spec type

- ansible_risk_insight/models.py
Added methods to MutableContent for adding new keys and values
> add a new method for mutation

- ansible_risk_insight/risk_detector.py
- follow the order in the rules config if it is provided
> follow the order in rules config

- ansible_risk_insight/analyzer.py
- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/dependency_finder.py
- ansible_risk_insight/finder.py
- ansible_risk_insight/loader.py
- ansible_risk_insight/logger.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/parser.py
- ansible_risk_insight/risk_detector.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/tree.py
- ansible_risk_insight/utils.py
- use a specific channel for logger (the channel is`ari` by default)
> use a specific channel for logger to avoid logger conflict

- ansible_risk_insight/rules/P004_variable_validation.py
- add an annotation `variable.unknown_name_vars` which is for undefined variables with a name different from the key name
> add annotation for unknown name vars

- ansible_risk_insight/models.py
- ansible_risk_insight/rules/P003_module_argument_value_validation.py
- improve primitive rule for module argument value handling
- update the related function of the MutableContent class
> improve the primitive rule for module argument value handling

- ansible_risk_insight/model_loader.py
- ansible_risk_insight/parser.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/tree.py
- add format error handling so that ARI can raise format error for invalid playbook YAML / task YAML if needed
> add format error handling

- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/rules/sample_rule.py
- docs/annotation.md
- docs/customize_rules.md
- update rule doc
- add sample rule
- fix misspellings
> update doc about rule and annotation

- ansible_risk_insight/model_loader.py
> fix a bug for playbook scan

- ansible_risk_insight/rules/sample_rule.py
- docs/annotation.md
> disable sample rule by default

- ansible_risk_insight/models.py
- ansible_risk_insight/scanner.py
- accept raw yaml input for playbook and taskfile scan
> accept raw yaml input for playbook and taskfile scan

- ansible_risk_insight/models.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/risk_detector.py
- record duration time in each rule result
- fix ram data handling when a module is not found in the index
> record duration time in each rule result

- ansible_risk_insight/cli/ram/__init__.py
- ansible_risk_insight/cli/ram/generate.py
- ansible_risk_insight/cli/ram/release.py
- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/models.py
- ansible_risk_insight/ram_generator.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/scanner.py
- added module index
- added RAM log file to control ram generation
- added `--no-retry` option to `ram generate` command
- added `ram release` command
> improve ram generator

- ansible_risk_insight/models.py
- ansible_risk_insight/risk_detector.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/utils.py
- enable spec mutation rule and re-scan after spec mutation
> enable spec mutation rule and re-scan after spec mutation

- ansible_risk_insight/_version.py
- release 0.1.0 as pypi package
> release 0.1.0 as pypi package

- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/keyutil.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/parser.py
- ansible_risk_insight/ram_generator.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/tree.py
- improve ram generate with indices for role and taskfile
> improve ram generate with indices for role and taskfile

- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/findings.py
- ansible_risk_insight/ram_generator.py
- remove unnecessary report from finding.json 
-  fix file paths in download metadata to avoid absolute path
> remove ari_report from ram data 

- ansible_risk_insight/annotators/ansible.builtin/unarchive.py
- ansible_risk_insight/cli/ram/generate.py
- ansible_risk_insight/finder.py
- ansible_risk_insight/findings.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/ram_generator.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/rules/R103_download_exec.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/utils.py
- test/test_scanner.py
- support include tests in ram generate mode
- support molecule
- fix annotators for some irregular input
> support include tests in ram generate mode

- ansible_risk_insight/cli/ram/generate.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/ram_generator.py
- ansible_risk_insight/scanner.py
- add out dir option to ram generate
- add `parent` to AnsibleRunContext
- add license_file contents to collection metadata
> add out dir option to ram generate

- ansible_risk_insight/findings.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/utils.py
- fix cache handling and filelock in ram generate
> fix cache handling and filelock in ram generate

- ansible_risk_insight/findings.py
- remove unnnecessary data from findings when it is saved
> remove unnnecessary data from findings when it is saved

- ansible_risk_insight/_version.py
> release 0.1.1

- ansible_risk_insight/cli/ram/generate.py
- add --serial option to ram generate command
> add --serial option to ram generate command

- ansible_risk_insight/dependency_dir_preparator.py
- fixed path of role archives data
- fixed bugs in using role archives data
> fix bug in using role archives data

- ansible_risk_insight/analyzer.py
- ansible_risk_insight/cli/ram/generate.py
- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/finder.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/ram_generator.py
- ansible_risk_insight/risk_detector.py
- ansible_risk_insight/scanner.py
> improve sequential scanning

- ansible_risk_insight/cli/__init__.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/risk_detector.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/tree.py
- fix dependency handling and improve performance
> fix dependency handling and improve performance

- ansible_risk_insight/context.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/tree.py
- fix handler loading
- fix collection dependency loading
- fix variable name detection
> fix handler and collection dependency

- ansible_risk_insight/dependency_dir_preparator.py
- fixed errors in preparing download metadata
- fixed to avoid installing dependencies when target is galaxy content
> fixed dependency dirs

- ansible_risk_insight/_version.py
- ansible_risk_insight/cli/__init__.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/tree.py
- fix ram initialization
- remove ram operation for taskfile/playbook/project scan
> fix ram initialization and remove ram operation for taskfile/playbook/project scan

- ansible_risk_insight/annotators/variable_resolver.py
- ansible_risk_insight/cli/__init__.py
- ansible_risk_insight/models.py
- ansible_risk_insight/rules/P001_module_name_validation.py
- ansible_risk_insight/scanner.py
- fix dependency issue and variable resolution
> fix dependency issue and variable resolution

- ansible_risk_insight/ram_generator.py
- ansible_risk_insight/scanner.py
- fix ram client initialize and improve ram generation speed
- improve ram generation console log
> fix ram client initialize and improve ram generation speed

- ansible_risk_insight/_version.py
> release 0.1.4

- ansible_risk_insight/risk_assessment_model.py
- fix ram client so it can handle module short name
> fix ram client so it can handle module short name

- ansible_risk_insight/risk_assessment_model.py
- fix ram client so it can suggest the best matched module
> fix ram client so it can suggest the best matched module

- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/dependency_finder.py
- ansible_risk_insight/findings.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/utils.py
- pyproject.toml
- fix filelock function to resolve race condition issue of indices
- fix the command execution error in newer python version when ARI runs in parallel
> fix filelock function to resolve race condition issue of indices

- ansible_risk_insight/_version.py
- ansible_risk_insight/awx_utils.py
- ansible_risk_insight/context.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/parser.py
- ansible_risk_insight/risk_detector.py
- ansible_risk_insight/rules/P002_module_argument_key_validation.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/tree.py
- ansible_risk_insight/utils.py
- fix loading roles and tests
- fix role loading for roles with dependencies
- fix taskfile loading in roles that are not included from main.yml
- fix test loading for roles
- enable rule exception only when a special error is raised
- fix annotations for `set_fact` module
> fix loading roles and tests

- ansible_risk_insight/rules/P003_module_argument_value_validation.py
> fix variable type detection in P003 rule

- ansible_risk_insight/awx_utils.py
- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/dependency_finder.py
- ansible_risk_insight/finder.py
- ansible_risk_insight/findings.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/parser.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/risk_detector.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/tree.py
- ansible_risk_insight/utils.py
- pyproject.toml
- add yml inventory functions (currently not integrated in main scanner flow)
- fix `yaml_lines` bug
- fix role dependency bug
> add yml inventory functions 

- ansible_risk_insight/yaml.py
- fix ruamel.yaml initialization
> fix ruamel.yaml initialization

- ansible_risk_insight/_version.py
- ansible_risk_insight/finder.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- fix yml_inventory functions
- add task_loading details to models
- fix yaml_lines detection
> fix yml_inventory functions and add task_loading details to models

- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/parser.py
- ansible_risk_insight/scanner.py
- fix playbook/taskfile filepath
> fix playbook/taskfile filepath

- ansible_risk_insight/yaml.py
- enable yaml indentation config
> enable yaml indentation config

- ansible_risk_insight/model_loader.py
- fix playbook detection logic
> fix playbook detection logic

- ansible_risk_insight/model_loader.py
- ansible_risk_insight/tree.py
- fix taskfile detection logic
> fix taskfile detection logic

- ansible_risk_insight/finder.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/risk_assessment_model.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/task_keywords.txt
- fix playbook detection and module info
> fix playbook detection and module info

- ansible_risk_insight/finder.py
> add type check to find_module_name

- ansible_risk_insight/_version.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/yaml.py
- enable yaml config
- fix inline task parameter handling
> enable yaml config and fix inline task parameter handling

- .github/workflows/test.yml
- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/finder.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/scanner.py
- fix path issue and inline module option issue
> fix path issue and inline module option issue

- ansible_risk_insight/finder.py
- update yml labeling function
> update yml labeling function

- ansible_risk_insight/utils.py
- fix taskfile path util function
> fix taskfile path util function

- ansible_risk_insight/yaml.py
- add yaml width config by default
> add yaml width config by default

- ansible_risk_insight/context.py
- fix dict variable handling for existence check
> fix dict variable handling for existence check

- ansible_risk_insight/dependency_finder.py
- fix project dependency issue
> fix project dependency issue

- ansible_risk_insight/tree.py
- fix to scan playbooks in role
> fix to scan playbooks in role

- ansible_risk_insight/awx_utils.py
- fix a util function to determine root directory of a project
> fix a util function to determine root directory of a project

- ansible_risk_insight/_version.py
> release 0.1.11

- ansible_risk_insight/finder.py
- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/safe_glob.py
- ansible_risk_insight/scanner.py
- ansible_risk_insight/tree.py
- fix issue around import resolution
> fix issue around import resolution

- ansible_risk_insight/_version.py
> release 0.2.0

- ansible_risk_insight/models.py
- ansible_risk_insight/tree.py
- update play role resolution to set info to RoleInPlay attribute
> update play role resolution to set info to RoleInPlay attribute

- ansible_risk_insight/models.py
- ansible_risk_insight/tree.py
- update play role resolution to set info to RoleInPlay attr
- add `role_info` to RoleInPlay object
- remove `roles_info` in Play object (this attr was not used by any codes)
> update play role resolution to set info to RoleInPlay attr

- scripts/gen_ram_subset.py
- enable to generate a subset of RAM from another RAM
usage:
```bash
python scripts/gen_ram_subset.py -d <SOURCE_RAM_DIR> -i <TARGET_LIST> -o <DESTINATION_SUBSET_DIR>
```
> enable to generate a subset of RAM from another RAM

- ansible_risk_insight/models.py
- fix rule result issue when multiple nodes have the same name
> fix rule result issue when multiple nodes have the same name

- scripts/gen_ram_slim.py
- add gen_ram_slim.py to convert ram-all to ram-slim
> add gen_ram_slim.py to convert ram-all to ram-slim

- ansible_risk_insight/_version.py
> release 0.2.1

- ansible_risk_insight/dependency_finder.py
- ansible_risk_insight/finder.py
- ansible_risk_insight/parser.py
- fix issues around duplicate taskfile loading
> fix issues around duplicate taskfile loading

- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- ansible_risk_insight/parser.py
- ansible_risk_insight/tree.py
- fix to load handlers in plays and to apply rules to them
> fix to load handlers in plays and to apply rules to them

- ansible_risk_insight/_version.py
update version string in _version.py
> update version string in _version.py (prep for releasing 0.2.2)

- ansible_risk_insight/dependency_dir_preparator.py
- ansible_risk_insight/scanner.py
- fixed download-only option of ram generate cli
- fixed a bug in collection installation
> fixed archives download

- ansible_risk_insight/model_loader.py
> update file object model

- ansible_risk_insight/_version.py
> prepare for releasing 0.2.3

- ansible_risk_insight/finder.py
- ansible_risk_insight/safe_glob.py
- add util function to search all files in directory
> add util function to search all files in directory

- ansible_risk_insight/finder.py
- ansible_risk_insight/tree.py
- update finder utils to improve taskfile detection
> update finder utils to improve taskfile detection

- ansible_risk_insight/risk_assessment_model.py
- fix module search for a module redirected from major collection
> fix module search for a module redirected from major collection

- ansible_risk_insight/_version.py
> prepare for releasing 0.2.4

- ansible_risk_insight/finder.py
- fix role info utility func for yml inventory
> fix role info utility func for yml inventory

- ansible_risk_insight/finder.py
- fix root path finder for collection
> fix root path finder for collection

- ansible_risk_insight/model_loader.py
- ansible_risk_insight/models.py
- fix line number detection for task loading
> fix line number detection for task loading

- ansible_risk_insight/risk_assessment_model.py
- fix module search issue when the first cand is deprecated
> fix module search issue when the first cand is deprecated

- ansible_risk_insight/rules/P001_module_name_validation.py
- fix module FQCN issue for import modules
> fix module FQCN issue for import modules

- ansible_risk_insight/_version.py
> prep for 0.2.5 release

- ansible_risk_insight/_version.py
> prep for 0.2.6 release

- ansible_risk_insight/finder.py
PR to fix extending tasks with module_defaults, issue raised under #222
> PR to fix extending tasks with module_defaults

- ansible_risk_insight/_version.py
> prep for 0.2.7 release

- README.md
- ansible_risk_insight/cli/__init__.py
- ansible_risk_insight/finder.py
PR to fix the ARI inline replace  functionality issue observed under issue #247
> PR to fix the ARI inline replace  functionality issue observed under issue 247

- ansible_risk_insight/_version.py
> prep for 0.2.8 release

- ansible_risk_insight/_version.py
> prep for 0.2.9 release

- ansible_risk_insight/context.py
- fix variable resolution issue for loop variables
> fix variable resolution issue for loop variables

- ansible_risk_insight/_version.py
> prep for 0.2.10 release
