ansible/ansible-risk-insight

ansible_risk_insight/dependency_dir_preparator.py, ansible_risk_insight/dependency_finder.py, ansible_risk_insight/scanner.py, ansible_risk_insight/utils.py
- improve metadata to include hash, download url, download timestamp etc.
- move root install function from scanner to dependency fir preparetor
=> update dependency dir preparetor

ansible_risk_insight/models.py, ansible_risk_insight/scanner.py
With the previous construction, two instances of the same class would share a
reference pointing on the same object.
This is likely to create unexpected behaviour and raise an error with
Python 3.11.
See: https://docs.python.org/3/library/dataclasses.html#mutable-default-values
=> dataclass: avoid the use of mutable default value

tox.ini
Introduce the use of `tox` as a more Pythonic alternative to `make`.
=> add a tox.ini file

ansible_risk_insight/cli/__init__.py, ansible_risk_insight/models.py, ansible_risk_insight/risk_detector.py, ansible_risk_insight/scanner.py, ansible_risk_insight/tree.py, ansible_risk_insight/utils.py
- enable to specify custom rule dirs with `--rules-dir` or `-r`
- support `-R` option too for ignoring default rules
=> enable to specify custom rule dirs with `--rules-dir`

ansible_risk_insight/cli/__init__.py, ansible_risk_insight/findings.py, ansible_risk_insight/models.py, ansible_risk_insight/risk_detector.py, ansible_risk_insight/rules/P001_module_name_validation.py, ansible_risk_insight/rules/P002_module_argument_key_validation.py, ansible_risk_insight/rules/P003_module_argument_value_validation.py, ansible_risk_insight/rules/P004_variable_validation.py, ansible_risk_insight/scanner.py
- `--out-dir` option will be used for the rule evaluation result instead of findings data
- findings will be treated as internal data in ARI after this change, and it will not be shown to a user normally
- change a class name TreeResult to TargetResult to make it more sense
=> rule result will be output by `--out-dir`

ansible_risk_insight/scanner.py
- fix an issue when the target is specified with a relative path
=> fix an issue when the target is specified with a relative path

ansible_risk_insight/cli/__init__.py, ansible_risk_insight/model_loader.py, ansible_risk_insight/models.py, ansible_risk_insight/parser.py, ansible_risk_insight/scanner.py
- support a playbook yaml input instead of filepath with `evaluate(playbook_yaml=yaml_string)`
=> support a playbook yaml input instead of filepath

ansible_risk_insight/risk_detector.py, ansible_risk_insight/scanner.py
- extend the config so that users can specify the rule ids to be used (if empty, use all rules)
- support setting configuration not only by env variables but also by file and by python object
=> extend config to specify rules

ansible_risk_insight/models.py
- add `omit_task_name()` function to MutableContent for more flexible content mutation
=> add omit_task_name() to MutableContent

ansible_risk_insight/models.py, ansible_risk_insight/rules/P001_module_name_validation.py
- use a custom yaml representer to avoid unnecessary newlines if some newlines are included in module arguments
- set correct FQCN info for tasks that uses include_role/include_tasks/import_role/import_tasks
=> improve mutation output with yaml formatter and support FQCN correction for include

ansible_risk_insight/risk_detector.py
- respect rule precedence more than rules config
- Even if ARIScanner was initialized with rules config like `rules=[R001, R002, R003]`, rule precedence is always more respected than the order in this config to determine the rule evaluation order.
=> respect rule precedence more than rules config of ARIScanner

ansible_risk_insight/models.py, ansible_risk_insight/rules/P003_module_argument_value_validation.py
- update a primitive rule to add 1 annotation for detecting a module arg value with undefined variables
=> add a primitive annotation to find a module arg value with undefined variables

ansible_risk_insight/cli/ram/generate.py, ansible_risk_insight/ram_generator.py
- add --no-module-spec option for ram generation without ansible-doc
=> add --no-module-spec option for ram generation without ansible-doc

ansible_risk_insight/models.py
- added methods for mutating task options
- renamed methods for mutating module options
=> update methods to mutate task option

ansible_risk_insight/rules/P003_module_argument_value_validation.py
- fix primitive rule for module value
=> fix primitive rule for module value

ansible_risk_insight/__init__.py, ansible_risk_insight/cli/__init__.py, ansible_risk_insight/dependency_dir_preparator.py, ansible_risk_insight/finder.py, ansible_risk_insight/model_loader.py, ansible_risk_insight/models.py, ansible_risk_insight/parser.py, ansible_risk_insight/risk_assessment_model.py, ansible_risk_insight/scanner.py, ansible_risk_insight/tree.py, ansible_risk_insight/utils.py
- support taskfile input both for CLI use and for SDK use
- only if the specified content is a taskfile, ARI handle the taskfile as a root of call tree. (normally the root is only playbooks or roles)
=> support taskfile input both for CLI and for SDK

ansible_risk_insight/risk_assessment_model.py
- fix ram release to not use absolute path in tar.gz
=> fix ram release to not use absolute path

ansible_risk_insight/models.py
- add `replace_module_arg_with_dict` to MutableContent
=> add `replace_module_arg_with_dict` to MutableContent

ansible_risk_insight/models.py
- support a task without module name
=> support a task without module name

ansible_risk_insight/model_loader.py, ansible_risk_insight/models.py
- fix taskfile loading issue for invalid input (e.g. taskfile but data is not a list )
```
---
name: Print hello world     <-- taskfile must be a list, but this is a dict because of missing "-"
debug:
msg: "Hello, world!"
```
=> fix taskfile loading issue for invalid input

ansible_risk_insight/analyzer.py, ansible_risk_insight/annotators/risk_annotator_base.py, ansible_risk_insight/risk_detector.py, ansible_risk_insight/scanner.py, ansible_risk_insight/utils.py
- fix to apply spec mutations to the loaded object in the second scan
- errors that occurred while applying rules will be reported as rule result instead of raising exceptions
=> fix to apply spec mutations to the loaded object

ansible_risk_insight/models.py
- add formatted_yaml() to dump task yaml in a fixed format
=> add formatted_yaml() to dump task yaml in a fixed format

ansible_risk_insight/cli/__init__.py, ansible_risk_insight/model_loader.py, ansible_risk_insight/models.py, ansible_risk_insight/parser.py, ansible_risk_insight/risk_assessment_model.py, ansible_risk_insight/risk_detector.py, ansible_risk_insight/rules/R204_unnecessary_set_fact.py, ansible_risk_insight/scanner.py
- add `--include-tests` option to load test contents in collections
- add `--objects` option to save objects definition
- fix several bugs
=> add `--include-tests` option to load test contents in collections

ansible_risk_insight/finder.py, ansible_risk_insight/ram_generator.py, ansible_risk_insight/scanner.py
- support `rescue` and `always` block as task definitions
- fix bugs around ram generate
=> support rescue and always block

ansible_risk_insight/model_loader.py, ansible_risk_insight/models.py, ansible_risk_insight/risk_assessment_model.py, ansible_risk_insight/tree.py
- support module redirect defined in collections
- e.g. ec2_group --> amazon.aws.ec2_security_group (defined [here](https://github.com/ansible-collections/amazon.aws/blob/d34cee63b8606628095f1ecd432101fc25f4b43f/meta/runtime.yml#L119-L121))
=> support module redirect defined in collections

ansible_risk_insight/dependency_dir_preparator.py
- enabled to use cache data when generating role ram
=> fixed bugs in role archive data handling

ansible_risk_insight/models.py
- fix initialization of `sequence` in AnsibleRunContext
The issue resolved by this PR
https://github.com/ansible/ansible-risk-insight/issues/134
=> fix initialization of `sequence` in AnsibleRunContext

ansible_risk_insight/loader.py, pyproject.toml
GitPackage is impacted by the following CVE-2022-24439, ARI doesn't use the
affect method, but the present of the package is enough to raise a warning in
Quay.io vulnerability scanner.
This commit move from GitPackage to pygit2 which provides similar feature set.
Also unkile GitPython, pygit2 doesn't require the presence of the `git` binary.
=> move from gitpackage to pygit2

ansible_risk_insight/risk_assessment_model.py
Previous code always took the first module returned; but if there are more than one we need to iterate and match on the fqcn
=> Fix: multiple modules with same short name but different collections

ansible_risk_insight/models.py, ansible_risk_insight/risk_detector.py
- enable rule exception only when a special error is raised
- An exception class `FatalRuleResultError` is newly added so that ARI can fail with exception. This is useful for some rules that detect fatal error in input data (e.g. no module name in task)
- all other exceptions are just stored in `error` attribute of rule result data and ARI never fails
=> enable rule exception only when a special error is raised

ansible_risk_insight/risk_detector.py, ansible_risk_insight/yaml.py
- fix thread safety issue of yaml parser by using `ContextVar` for ruamel.yaml.YAML instance
- fix rule result handling
=> fix concurrency issue of yaml parser

ansible_risk_insight/scanner.py
- fix dependency scanning issue when the target path does not exist
=> fix dependency scanning issue when the target path does not exist

ansible_risk_insight/dependency_dir_preparator.py, ansible_risk_insight/dependency_finder.py, ansible_risk_insight/scanner.py, ansible_risk_insight/utils.py
- enable to use ansible path
- if `use_ansible_path` is True in `evaluate()` arguments, ARI reads ansible configuration for ansible dir (`~/.ansible` by default) and it tries to find dependency dirs in the ansible directory. This feature is disabled by default.
=> enable to use ansible path

scripts/gen_ram_slim.py
- fix scripts/gen_ram_slim.py so that it can handle redirects configs
=> fix scripts/gen_ram_slim.py so that it can handle redirects configs 

ansible_risk_insight/models.py
- enable to set task name to mutable content
=> enable to set task name to mutable content

ansible_risk_insight/rules/P003_module_argument_value_validation.py, ansible_risk_insight/rules/P004_variable_validation.py
- fix P-rules to avoid reporting registered vars as undefined
=> fix P-rules to avoid reporting registered vars as undefined

ansible_risk_insight/yaml.py
- add workaround for a multi thread issue of ruamel.yaml [[detail](https://sourceforge.net/p/ruamel-yaml/tickets/367/)]
=> add workaround for a multi thread issue of ruamel.yaml

ansible_risk_insight/yaml.py
- fix wrong yaml instance type (`rt` is a right instance type to use ruamel.yaml functionalities; `safe` is a mode to use PyYAML package instead)
=> fix wrong yaml instance type

ansible_risk_insight/finder.py, ansible_risk_insight/keyutil.py, ansible_risk_insight/model_loader.py, ansible_risk_insight/models.py, ansible_risk_insight/parser.py
- add file object model and loading function
=> add file object model and loading function

ansible_risk_insight/rules/P002_module_argument_key_validation.py, ansible_risk_insight/rules/P003_module_argument_value_validation.py
- fix type check in P-rules for special modules
=> fix type check in P-rules for special modules

ansible_risk_insight/model_loader.py
- fix play condition in loader to handle playbooks with wrong keywords
=> fix play condition in loader to handle playbooks with wrong keywords

ansible_risk_insight/model_loader.py, ansible_risk_insight/models.py, ansible_risk_insight/scanner.py
- support vars files
- add `encrypted` flag to File object for Vault file
- fix loop handling issue
- fix filepath issue for YAML string scan
=> support vars files and fix several issues

ansible_risk_insight/model_loader.py
- fix filepath issue for yaml string scan
=> fix filepath issue for yaml string scan

ansible_risk_insight/model_loader.py
- fix path issue around repo root and yaml_label_list
=> fix path issue around repo root and yaml_label_list

ansible_risk_insight/cli/__init__.py
- add `--skip-isolated-taskfiles` option to CLI args
- If specified, `load_all_taskfiles` option of `evaluate()` function becomes `false`. Otherwise, it is `true` by default for CLI execution.
Issue: https://github.com/ansible/ansible-risk-insight/issues/221
=> add `--skip-isolated-taskfiles` option to CLI args

ansible_risk_insight/scanner.py
PR to pass ARI config path as env var, where user has the option to pass ARI config path as ENV. variable. If not ARI config path would be defaulted to path `~/.ari/config`.
=> PR to pass ARI config path as env var

ansible_risk_insight/annotators/ansible.builtin/unarchive.py, ansible_risk_insight/dependency_finder.py, ansible_risk_insight/model_loader.py, ansible_risk_insight/models.py, ansible_risk_insight/utils.py, pyproject.toml
- remove ansible-core dependency
=> remove ansible-core dependency

ansible_risk_insight/cli/__init__.py, ansible_risk_insight/model_loader.py, ansible_risk_insight/risk_detector.py, ansible_risk_insight/scanner.py
- add --save-only-rule-result option to reduce file size of `rule_result.json`
=> add --save-only-rule-result option

ansible_risk_insight/cli/__init__.py, ansible_risk_insight/finder.py, ansible_risk_insight/risk_detector.py
- add --scan-per-target option which enables to output result files per target
- target can be `playbook`, `role` and `taskfile` which is not in a role
=> add --scan-per-target option which enables to output result files per target

ansible_risk_insight/finder.py, ansible_risk_insight/model_loader.py, ansible_risk_insight/models.py, ansible_risk_insight/risk_detector.py
=> support local_action tasks

ansible_risk_insight/model_loader.py
PR to fix ari truncated output issue in case of module option value parameter. Fixes issue #223 
Input Play:
```
---
- name: Define timestamp
set_fact: timestamp="{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
run_once: true
```
Output play w/o the fix:
```
- name: Define timestamp
run_once: true
ansible.builtin.set_fact:
timestamp: "{{"
```
Output play with the fix:
```
- name: Define timestamp
run_once: true
ansible.builtin.set_fact:
timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
```
=> PR to fix ari truncated output issue in case of module option value parameter

ansible_risk_insight/cli/__init__.py, ansible_risk_insight/finder.py
PR update inline replace '--fix' implementation logic
=> PR update inline replace '--fix' implementation logic 

ansible_risk_insight/finder.py, ansible_risk_insight/models.py, test/test_inline_replace.py, test/testdata/inline_replace_data/block_and_when_play.yml, test/testdata/inline_replace_data/block_and_when_play_fixed.yml
PR to fix to correctly identify task based on Ansible block and when indentation. Fixes issues reported under #232
=> PR to fix to correctly identify task based on Ansible block and when indentation

ansible_risk_insight/finder.py, ansible_risk_insight/model_loader.py, ansible_risk_insight/models.py, test/test_scanner.py, test/testdata/files/test_line_number.yml
- fix the following 2 issues about line number detection 
- https://github.com/ansible/ansible-risk-insight/issues/251
- https://github.com/ansible/ansible-risk-insight/issues/252
=> fix line number detection bug

ansible_risk_insight/cli/__init__.py, ansible_risk_insight/finder.py, ansible_risk_insight/model_loader.py, ansible_risk_insight/parser.py, ansible_risk_insight/ram_generator.py, ansible_risk_insight/rules/sample_rule.py, ansible_risk_insight/tree.py, ansible_risk_insight/yaml_utils.py
- fix an issue of role/taskfile detection when some playbooks/taskfiles are in `roles/tasks`
- fix an issue where `yaml_label_list` was not correctly used for loading taskfiles
=> fix an issue of role/taskfile detction with specific path

ansible_risk_insight/finder.py, test/test_scanner.py, test/testdata/files/test_line_number.yml, test/testdata/files/test_line_number2.yml
- fix line number detection bug with empty lines
=> fix line number detection bug with empty lines

ansible_risk_insight/model_loader.py, ansible_risk_insight/ram_generator.py, ansible_risk_insight/scanner.py
Getting below warning messages while running test cases in app
>  /.../python3.12/site-packages/ansible_risk_insight/scanner.py:1236: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
time_records[record_name]["begin"] = datetime.datetime.utcnow().isoformat()
>  /.../python3.12/site-packages/ansible_risk_insight/scanner.py:1239: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
end = datetime.datetime.utcnow()
>  /.../python3.12/site-packages/ansible_risk_insight/model_loader.py:2009: …
=> (fix) `datetime.datetime.utcnow()` deprecation warning
